img_params:
  w: 800 #拼接图宽度
  h: 800 #拼接图高度
stitch_params:
  bev_ratio: 0.02 #拼接图一个像素代表的实际物理距离（米）
  center_x: 400 #定位原点在拼接图上的像素x坐标（像素）
  center_y: 489.65 #定位原点在拼接图上的像素y坐标（像素）
  shift_lr: 350 #黑边离图像左右两侧的距离，当前拼接图左右对称(像素)
  shift_tb: 266 #黑边离图像上下两侧的距离，当前拼接图上下对称(像素)
filter_kernel_size: 25 #平滑卷积核大小